name: Java Matrix CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Java 17 test build
    steps:
    - name: "Check out code"
      uses: actions/checkout@v4
    - name: "Set up JDK"
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: "zulu"
        cache: 'maven'
    - name: "Build with Maven"
      run: mvn -B clean install
