name: Java Matrix CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Java 21 test build
    steps:
    - name: "Check out code"
      uses: actions/checkout@v5
    - name: "Set up JDK"
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: "zulu"
        cache: 'maven'
    - name: "Build with Maven"
      run: mvn -B clean install
